models:
  - type: main
    engine: nim
    model: meta/llama-3.1-8b-instruct
    api_key_env_var: NVIDIA_API_KEY

rails:
  config:
    # PII - NVIDIA GLiNER NIM
    gliner:
      server_endpoint: https://integrate.api.nvidia.com/v1/chat/completions
      api_key_env_var: NVIDIA_API_KEY
      input:
        entities:
          - email
          - first_name
          - last_name
          - phone_number
          - ssn
      output:
        entities:
          - email
          - first_name
          - last_name
          - phone_number
          - ssn
          
  input:
    flows:
      - gliner mask pii on input
      - check restricted topics
      - check jailbreak
  output:
    flows:
      - check hallucinations
      - check polish language
      - check fact checking
      - gliner mask pii on output