models:
  - type: main
    engine: openai
    model: gemini-3.5-flash-lite
    api_key_env_var: GOOGLE_API_KEY
    parameters:
      base_url: "https://generativelanguage.googleapis.com/v1beta/openai/"
rails:
  input:
    flows:
      - mask sensitive data on input
      - check jailbreak
      - check off topic
  output:
    flows:
      - check hallucinations
      - check polish language
      - mask sensitive data on output